### ISSUE TITLE
HASH: Out of overflow pages.  Increase page size

### ISSUE THREAD

**Issue by Folco1975** [google/categorybuilder#12]
hi,
I'm trying to run  python3 initialize.py after installing.... (python 3.7)

I receive an error:
Initializing two matrices.
Checking if we need to produce './i-to-f-shelf' from './candidate_release-i-to-f.csv.bz2'
Processing './candidate_release-i-to-f.csv.bz2'. This may take a few minutes.
HASH: Out of overflow pages.  Increase page size
Traceback (most recent call last):
  File "initialize.py", line 21, in <module>
    util.CreateShelves(True)
  File "/categorybuilder/category_builder_util.py", line 104, in CreateShelves
    CreateShelf(GetPath(I_TO_F_INPUT), GetPath(I_TO_F_SHELF), linecount=200000, verbose=verbose)
  File "/categorybuilder/category_builder_util.py", line 94, in CreateShelf
    s[key] = rest.strip()
  File "/Users/stefano/anaconda3/lib/python3.7/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database

Thank yuo for any help.

**Comment by amahabal** [comment]
Hi Folco,

You seem to be running out of memory. What machine are you running on?

The memory footprint of the matrix creation is large, but that of actually using the matrices is much smaller. We will try other alternatives for the matrix creation that are lighter on memory.

Thanks,
  Abhijit

**Comment by Folco1975** [comment]
Hi,

Thank you for writing.
I’m running it on my MacBook Pro with 32GB of memory.

Is there any way to tell the system to use more memory or I have to stop all others services?



Thank you again.
Stefano..

Ing. Stefano Santo Sabato, PhD
Founder & CTO
MediaSoft srl
Sede di 73013 Galatina - Via Sonzini, 25
Tel. 0836.564849 - Fax 0836.843111
Sede di 00187 Roma - Piazza del Popolo, 18
Sede di 37133 Verona - Vicolo Valle, 9
 
MediaSoft US c/o Fyberloom Inc.
95 Third Street 2nd Floor - San Francisco - CA 94103 - USA
 
Web: www.mediasoftonline.com

On May 5, 2020 at 10:22:39 AM, Abhijit Mahabal (notifications@github.com) wrote:

Hi Falco,

You seem to be running out of memory. What machine are you running on?

The memory footprint of the matrix creation is large, but that of actually using the matrices is much smaller. We will try other alternatives for the matrix creation that are lighter on memory.

Thanks,
Abhijit

**Comment by amahabal** [comment]
Hi Stefano,

I have been meaning to switch to a lighter system anyway (specifically, sqlite). So, let me bite that bullet, and hopefully I will have made the process cheaper by tomorrow. Stay tuned.

**Comment by Folco1975** [comment]
Thank you !

I will stay tuned!

Talk soon,
Stefano.


Ing. Stefano Santo Sabato, PhD
Founder & CTO
MediaSoft srl
Sede di 73013 Galatina - Via Sonzini, 25
Tel. 0836.564849 - Fax 0836.843111
Sede di 00187 Roma - Piazza del Popolo, 18
Sede di 37133 Verona - Vicolo Valle, 9
 
MediaSoft US c/o Fyberloom Inc.
95 Third Street 2nd Floor - San Francisco - CA 94103 - USA
 
Web: www.mediasoftonline.com

On May 5, 2020 at 10:40:26 AM, Abhijit Mahabal (notifications@github.com) wrote:

Hi Stefano,

I have been meaning to switch to a lighter system anyway (specifically, sqlite). So, let me bite that bullet, and hopefully I will have made the process cheaper by tomorrow. Stay tuned.

**Comment by amahabal** [comment]
Hi Stefano,

Can you try again?

Best,
  Abhijit

**Comment by Folco1975** [comment]
Hi, It Works ! Thank you !
