### ISSUE TITLE
initialize.py throwing compilation error

### ISSUE THREAD

**Issue by smrdhkh** [google/categorybuilder#4]
After running python initialize.py cmd this error came --

Traceback (most recent call last):
  File "initialize.py", line 18, in <module>
    import category_builder_util as util
  File "C:\Users\samy\categorybuilder\category_builder_util.py", line 63
    print "Checking if we need to produce '%s' from '%s'" % (outfile, infile)
                                                        ^
SyntaxError: invalid syntax

**Comment by amahabal** [comment]
Hi Samridhi,

Thanks for the report.

What is the OS and python version?

Please also provide the directory listing of the ("ls" for Unix or Linux),
since the shelf file generated can have different names based on your setup.

Thanks!
  Abhijit

**Comment by smrdhkh** [comment]
Windows 10 and python 3.7.0
07/04/2018  07:51 PM    <DIR>          .
07/04/2018  07:51 PM    <DIR>          ..
07/04/2018  07:33 PM                43 .gitattributes
07/04/2018  07:33 PM                15 .gitignore
07/04/2018  07:33 PM                81 .mailmap
07/04/2018  07:33 PM             1,209 analogy.py
07/04/2018  07:51 PM     1,052,979,042 candidate_release-f-to-i.csv.bz2
07/04/2018  07:43 PM       582,323,067 candidate_release-i-to-f.csv.bz2
07/04/2018  07:34 PM             1,624 category_builder.py
07/04/2018  07:34 PM           237,157 category_builder_paper.pdf
07/04/2018  07:34 PM             6,812 category_builder_util.py
07/04/2018  07:33 PM             1,129 CONTRIBUTING.md
07/04/2018  07:34 PM               783 initialize.py
07/04/2018  07:33 PM            11,560 LICENSE
07/04/2018  07:33 PM             2,979 README.md
              13 File(s)  1,635,565,501 bytes
               2 Dir(s)  267,832,827,904 bytes free

**Comment by amahabal** [comment]
This is python 2 code. Can you please start from a clean pull and use
python 2?

Thanks!
