### ISSUE TITLE
Undefined variable in `analogy` evaluations

### ISSUE THREAD

**Issue by danyaljj** [google/categorybuilder#6]
In the analogy evaluations, there seems to be an undefined variable: `use_plain_ppmi `: 
https://github.com/google/categorybuilder/blob/master/eval_analogy.py#L95

FYI @amahabal

**Comment by amahabal** [comment]
Sorry for the late reply: my excuse is that I left Google and did not receive this bug report. This has been fixed in the latest updates.

Best,
  Abhijit
