### ISSUE TITLE
does not support py3

### ISSUE THREAD

**Issue by unnat-ed** [google/categorybuilder#9]
Even after the recent bugfixes the code doesn't support python3

**Comment by amahabal** [comment]
Thanks for the report. I will update this this week to make it work in Python3.

**Comment by amahabal** [comment]
Hi Shivansh,

I am no longer at Google, so I seem to have lost write access. But I updated to Python3, here:  https://github.com/amahabal/categorybuilder

Please do let me know whether this worked for you (amahabal@gmail.com).

Thanks!
  Abhijit

**Comment by amahabal** [comment]
And updated in this repo as well.
